Add program notifications
EuroPython/discord pull request #134
Opened 2024-06-17 22:51 UTC by egeakman

2024-06-28 23:06 UTC, NMertsch requested changes
Hi @egeakman, thanks a lot for all this work!
I have a few suggestions and requests for the main code. None of them are critical, but please have a look at them.

What's critical to me is that your tests are not self-contained. They will fail depending on external factors (in this case `https://programapi24.europython.eu/2024/schedule.json`), not depending on the code that's supposed to be tested.
You might find some inspiration in the tests for `PretixConnector`.

Since it is quite close to the conference and your code is working, I'm okay with merging and deploying this now and working on the code after the conference or during the sprints.

2024-06-28 23:13 UTC, NMertsch commented
What I forgot in my review: I don't like using dictionaries instead of (data)classes. That's very easy to mess up and no tool can help you with keeping the structure aligned in all places.

2024-06-29 17:11 UTC, egeakman commented on .gitignore
> +schedule.json
I wasn't initially thinking of making it persistent, but let's do it for good measure.

2024-06-29 17:12 UTC, egeakman commented on EuroPythonBot/config.toml
> +timezone = 2
Yes, somehow I forgot to rename this. Thank you!

2024-06-29 17:14 UTC, egeakman commented on EuroPythonBot/configuration.py
> +            self.PROGRAM_CHANNELS = {
It is ``Optional testing parameters`` in ``Program Notifications`` :D How can I nest it categorically?

I did MarkDown style ``#`` for category, and ``##`` for sub category first; but flake didn't like it.

2024-06-29 17:15 UTC, egeakman commented on EuroPythonBot/configuration.py
> +            self.PROGRAM_CHANNELS = {
Thank you!

2024-06-29 17:16 UTC, egeakman commented on EuroPythonBot/program_notifications/cog.py
Yep, was thinking about doing something similar to this. Thanks!

2024-06-29 17:23 UTC, egeakman commented on EuroPythonBot/program_notifications/cog.py
> +    async def fetch_schedule(self):
Hmm, you are right. In the current version, we write the schedule to the ``cache_file`` in every successful fetch. But we also write it to the memory, so it's unnecessary to load the cached_schedule when the fetch fails, instead, we can keep using the one in memory.

Funny how I missed something like this :facepalm:

2024-06-29 17:23 UTC, egeakman commented on EuroPythonBot/program_notifications/cog.py
> +            except FileNotFoundError:
:+1:

2024-06-29 17:29 UTC, egeakman commented on EuroPythonBot/program_notifications/cog.py
> +    @tasks.loop(seconds=1)
Yet another thing I forgot to change before pushing. 15 seconds didn't work when I was testing it with a high time multiplier. But that was only for testing purposes.

So any number that fits ``2 * seconds < 300`` should work for a time multiplier of ``1``.

2024-06-29 17:30 UTC, egeakman commented on EuroPythonBot/program_notifications/cog.py
> +    @tasks.loop(seconds=1)
We can add some additional code that calculates the maximum amount of time given the time multiplier, in order to make it work when testing.

2024-06-29 17:32 UTC, egeakman commented on EuroPythonBot/program_notifications/cog.py
> +        if upcoming_sessions:
Thank you!

2024-06-29 17:32 UTC, egeakman commented on EuroPythonBot/program_notifications/cog.py
> +            self.notified_sessions.update(session.code for session in upcoming_sessions)
Yes.

2024-06-29 17:32 UTC, egeakman commented on EuroPythonBot/program_notifications/cog.py
> +    async def on_ready(self):
:+1:

2024-06-29 17:34 UTC, egeakman commented on EuroPythonBot/program_notifications/cog.py
> +                )
Looks better, thanks.

2024-06-29 17:34 UTC, egeakman commented on EuroPythonBot/program_notifications/program_connector.py
> +        self._timezone_offset = timezone_offset
Makes sense, thanks.

2024-06-29 17:35 UTC, egeakman commented on EuroPythonBot/program_notifications/program_connector.py
> +        self.sessions_by_day: dict[datetime, list[Session]] | None = None
Another missed thing, thank you.

2024-06-29 17:36 UTC, egeakman commented on EuroPythonBot/program_notifications/program_connector.py
> +            and session.start > now
#TodayILearned :heart:

2024-06-29 17:37 UTC, egeakman commented on EuroPythonBot/program_notifications/session_to_embed.py
> +    "beginner": 6542417,
Was just using the last year's code, this is better. Thanks.

2024-06-29 17:38 UTC, egeakman commented on EuroPythonBot/program_notifications/session_to_embed.py
> +        description=_create_description(session) if session.tweet else None,
:+1:

2024-06-29 17:41 UTC, egeakman commented on EuroPythonBot/program_notifications/session_to_embed.py
> +        url=str(session.website_url) if session.website_url else None,
IIRC the Program API sent ``""`` in order to keep the required changes minimal in the website. But it'd be better practice to send ``null`` instead of empty strings in general. Thank you.

2024-06-29 17:44 UTC, egeakman commented on EuroPythonBot/program_notifications/session_to_embed.py
> +    for field in fields:
Yes, this looks better, let's have it like this. I just didn't bother to change last year's code here :D

2024-06-29 17:45 UTC, egeakman commented on EuroPythonBot/program_notifications/session_to_embed.py
> +    )
Last year's code as well. I'll update it.

2024-06-29 17:46 UTC, egeakman commented on EuroPythonBot/program_notifications/session_to_embed.py
> +    except KeyError:
Yes we can :)

2024-06-29 17:46 UTC, egeakman commented on tests/program_notifications/test_program_connector.py
Would you like me to create a local copy here in this repo?

2024-06-29 17:47 UTC, egeakman commented on tests/program_notifications/test_program_connector.py
> +        cache_file=tmp_path / "test_cache_schedule.json",
YATIM (yet another thing I missed) :D

2024-06-29 17:49 UTC, egeakman commented on tests/program_notifications/test_session_to_embed.py
Yes, thank you. One more YATIM

2024-06-30 02:43 UTC, egeakman commented
Things to do tomorrow:
- Address comments on ``session_to_embed``
- Fix tests

2024-06-30 10:34 UTC, NMertsch commented on tests/program_notifications/test_program_connector.py
No, not a full copy. Just enough data to test the code.

2024-06-30 10:34 UTC, NMertsch commented on EuroPythonBot/program_notifications/cog.py
> +        await self.purge_all_room_channels()
Do we really want this? I thought participants can use the room channels to discuss talks, ask questions, and so on. If all these messages are purged on a bot restart, that's probably an issue.

2024-06-30 10:38 UTC, NMertsch commented on EuroPythonBot/program_notifications/session_to_embed.py
> +        url=str(session.website_url) if session.website_url else None,
FYI, not something we should do now: With a pydantic validator we could automatically convert empty strings to `None`.
Maybe after the event :)

2024-06-30 11:54 UTC, NMertsch commented on EuroPythonBot/program_notifications/cog.py
> +    @tasks.loop(seconds=1)
Thanks, didn't think of the time multiplier for testing. Let's not be too clever here.
Can we limit the time multiplier so that it always works with 15s? Or have `fast_mode=true/false` instead of a configurable multiplier?

2024-06-30 13:37 UTC, egeakman commented on EuroPythonBot/program_notifications/cog.py
> +        await self.purge_all_room_channels()
We probably don't. I added this because I constantly ran the bot and the messages piled up, the easiest way was to purge all the channels.

I'll make it purge the channels only when testing.

2024-06-30 20:09 UTC, NMertsch approved these changes
These tests are much better than before! :)
I made a few minor comments, please read them and decide if you want to act on them or not.

I personally try to avoid dynamic test data as much as possible, e.g. `datetime.now()`, and like to use very small dummy test data like `"Wednesday Talk Title 1"` instead of real strings to reduce the cognitive load, but that's a matter of preference, not of good or bad.

Thank you very much for this contribution! Please merge when you are ready.

2024-06-30 20:09 UTC, NMertsch commented on tests/program_notifications/test_program_connector.py
> +        return web.Response(status=500)
Please import [http.HTTPStatus](https://docs.python.org/3/library/http.html#http.HTTPStatus) and use `status=HTTPStatus.INTERNAL_SERVER_ERROR` or another error code.

Then you can also remove the comment "should be higher than 400", because your code already contains "status is an error status".

2024-06-30 20:09 UTC, NMertsch commented on tests/program_notifications/test_program_connector.py
> +async def test_get_now(program_connector):
This should be two tests, e.g. `test_get_now_with_simulation()` and `test_get_now_without_simulation()`.

2024-06-30 20:09 UTC, NMertsch commented on tests/program_notifications/test_program_connector.py
> +    program_connector._real_start_time = datetime.now(tz=timezone.utc)
Please use a fixed datetime here (and later in the same test).

2024-06-30 21:37 UTC, egeakman commented on tests/program_notifications/test_program_connector.py
> +    program_connector._real_start_time = datetime.now(tz=timezone.utc)
Thanks, @NMertsch for the suggestion!

Since the ProgramConnector._get_now calls datetime.datetime.now internally, it only works when the actual start time of the script is provided.

Otherwise, it produces results that don't make sense because it compares the random _real_start_time with the actual current time.

And that's why it is private and set automatically in the class initialization.

I'd want to implement this, but doing so will take too much time, and we don't have that until two weeks later :slightly_smiling_face:

2024-07-01 01:48 UTC, egeakman commented
I think all comments are taken care of and this is ready to be merged. Can you do a final check @NMertsch?

2024-07-01 07:53 UTC, NMertsch requested changes

2024-07-01 07:53 UTC, NMertsch commented on tests/program_notifications/test_session_to_embed.py
Hi @egeakman, with these tests you don't check if `session_to_embed(session)` produces the intended result. You are only testing that the function is calling the correct sub-functions (e.g. `_format_title(session.title)`).

If I replace the body of `_format_title(session.title)` with `return ""`, the tests would still pass. The same applies to most other tests.

2024-07-01 07:53 UTC, NMertsch commented on tests/program_notifications/test_program_connector.py
> +    assert await program_connector._get_now() < simulated_start_time
This fails 90% of the time on my machine because both values are equal. I have to add `time.sleep(0.000001)` before the `assert` to make it pass consistently.

Looks like a race condition: If the test runs too quickly, `_get_now()` returns the start time.

2024-07-01 07:59 UTC, NMertsch commented on tests/program_notifications/test_program_connector.py
> +    time.sleep(0.1)
```suggestion
    time.sleep(0.001)  # ensure time is ticking between start and finish of this test
```

2024-07-01 08:33 UTC, NMertsch commented
@egeakman Here is an example of how I would test the embed title in `test_session_to_embed.py`:
- A fixture is creating a generic `Session` object for each test
- Each test sets up the tested aspect of the `Session` object (e.g. `session.title = "Short Title"`)
- Each test calls `create_session_embed(session)`
- Each test makes assertions about the tested aspect of the `Embed` object (e.g. `assert embed.title == "Short Title"`)

This way, the test code itself contains the information about the test: Arrange, Act, Assert. The fixture is doing generic setup logic: Our test requires that "a session is created", but does not care about "how the session is created". Also, it cares about the title of the session, but it does not care about all the other fields of it.

```python
from datetime import datetime, timezone

import pytest

from program_notifications.session_to_embed import create_session_embed
from program_notifications.models import Session, Speaker


@pytest.fixture
def session() -> Session:
    """Create a dummy session object."""
    return Session(
        code="AAAAAA",
        duration=60,
        event_type="session",
        level="beginner",
        rooms=["Exhibit Hall", "Forum Hall"],
        session_type="Announcements",
        slug="example-session",
        speakers=[Speaker(code="BBBBBB", name="Jane Doe", avatar="", website_url="")],
        start="2024-07-10T08:00:00+00:00",
        title="Example Session",
        track=None,
        tweet="",
        website_url="",
    )


def test_short_title(session: Session) -> None:
    session.title = "Short Session Title"

    embed = create_session_embed(session)
    assert embed.title == "Short Session Title"


def test_long_title(session: Session) -> None:
    session.title = (
        "This is a long title which exceeds our maximum embed title length, "
        "so we expect it to be shortened by our session-to-embed converter. "
    )

    embed = create_session_embed(session)
    assert embed.title == (
        "This is a long title which exceeds our maximum embed title length, "
        "so we expect it to be shortened by our session-to-embed [...]"
    )
```

2024-07-01 13:43 UTC, NMertsch requested changes
Please fix `test_get_now_with_simulation`, then this can get merged.
I have a few nitpicks about the tests, but let's talk about that in Prague. Thanks a lot @egeakman for this huge effort!

2024-07-01 13:43 UTC, NMertsch commented on tests/program_notifications/test_session_to_embed.py
> +def test_get_color(session: Session) -> None:
This could be three tests, done via [pytest.mark.parametrize](https://docs.pytest.org/en/7.0.x/how-to/parametrize.html).

Or you drop this test because you already have `test_embed_color()` above (which could be parametrized).

2024-07-01 13:43 UTC, NMertsch commented on tests/program_notifications/test_session_to_embed.py
> +    if session.track:
if/else should be avoided in tests: What are we actually testing here?

2024-07-01 13:43 UTC, NMertsch commented on tests/program_notifications/test_program_connector.py
> +    program_connector._time_multiplier = 1000
This doesn't solve it on my machine. `0 * 1000` is still zero.

The issue is that "real" time is continuous, but "computer" time is discrete. So if you call `datetime.now()` twice in a very short "real" time period, both calls can return the exact same "computer" time. Then the "computer" time difference is exactly zero, and multiplying zero with a large number still returns zero.

2024-07-01 19:21 UTC, egeakman commented
> Please fix test_get_now_with_simulation, then this can get merged.

Should be ready to merge, then!

2024-07-01 19:44 UTC, merged